// All text on tapmi.pl, Polish and English side by side. Short by design:
// the UX pass cut every section to a few words on phones; details live in
// the FAQ. {PLACEHOLDERS} come from config.js via build.js.
module.exports = {
  pl: {
    lang: 'pl', other: 'en', otherLabel: 'EN', otherHref: '/en/', langLabel: 'English version',
    title: 'Opinie Google dla restauracji – karty NFC | TapMi',
    description: 'Karta NFC na stoliku: goście oceniają wizytę w kilka sekund, a o niskiej ocenie wiesz od razu. Więcej zaproszeń do opinii Google, zgodnie z zasadami.',
    nav: { how: 'Jak to działa', owner: 'Alerty', features: 'Funkcje', groups: 'Dla grup lokali', faq: 'FAQ', login: 'Zaloguj się', cta: 'Umów demo', menu: 'Otwórz menu' },
    skip: 'Przejdź do treści',
    hero: {
      eyebrow: 'Opinie Google i oceny gości · restauracje, kawiarnie, hotele',
      title: 'Zadowoleni goście, zgrany zespół.',
      lead: 'Gość ocenia w 5 sekund. Ty wiesz od razu.',
      cta: 'Umów bezpłatne demo', secondary: 'Zobacz, jak to działa',
      chips: [['phone', 'Bez aplikacji'], ['shield', 'Zgodne z Google'], ['check', 'Telefon i PC']],
    },
    mock: {
      venue: 'Bistro Pod Lipą', question: 'Jak oceniasz swoją wizytę?', note: '+ Prywatna wiadomość dla zespołu', google: 'Oceń nas w Google',
      notifTime: 'teraz', notifVenue: 'Bistro Pod Lipą', notifBody: 'Obsługa: Ania · „Długo czekaliśmy na deser.”', notifTip: 'Podejdź do stolika — najpierw wysłuchaj.',
      avg: 'Śr. ocena · 7 dni', ratings: '58 ocen', caption: 'Tak działa TapMi: gość przykłada telefon do karty, ocenia, a właściciel od razu dostaje alert i widzi wynik w panelu.',
      pause: 'Wstrzymaj animację', play: 'Wznów animację',
    },
    how: {
      eyebrow: 'Jak to działa', title: 'Trzy kroki, kilka sekund',
      steps: [
        ['Gość przykłada telefon', 'Do karty NFC — albo skanuje kod QR.'],
        ['Ocenia gwiazdkami', 'Potem to samo zaproszenie do Google dla każdego.'],
        ['Ty wiesz od razu', 'Ocena 1–3★ przychodzi na Twój telefon.'],
      ],
    },
    owner: {
      eyebrow: 'Alerty', title: 'Gdy coś nie zagra, masz jeszcze chwilę',
      body: 'Alert przychodzi, póki gość jest przy stoliku. Podejdź, wysłuchaj, zamknij sprawę jednym dotknięciem.',
      small: 'Każdy alert przypomina: nie wspominaj o ocenie i nie proś o jej zmianę.',
      resolved: 'Załatwione', resolvedNote: 'Deser na koszt lokalu',
    },
    google: {
      eyebrow: 'Zgodność z Google', title: 'To samo zaproszenie dla każdego',
      body: 'Każda ocena, od 1 do 5★, widzi ten sam przycisk Google. Prywatna wiadomość to dodatek — nigdy zamiast opinii.',
      caption: 'Ten sam przycisk przy każdej ocenie',
    },
    features: {
      eyebrow: 'Funkcje', title: 'Wszystko, czego potrzebujesz', swipe: 'Przesuń, aby zobaczyć więcej',
      items: [
        ['phone', 'Ocena w kilka sekund', 'Bez aplikacji, PL/UA/EN, Twoje logo i kolory.'],
        ['bell', 'Alert na telefon i e-mail', 'Ocena 1–3★ na telefon w kilka sekund.'],
        ['check', 'Panel, który mówi, co ważne', 'Od razu widzisz, co czeka na reakcję.'],
        ['users', 'Oceny obsługi', 'Kogo goście chwalą — uczciwie, od 15 ocen.'],
        ['search', 'Komentarze i statystyki', 'Szukaj w komentarzach, eksport do Excela.'],
        ['heart', 'Przycisk Instagrama', 'Po ocenie: „Obserwuj nas na Instagramie”.'],
      ],
    },
    groups: {
      eyebrow: 'Dla grup lokali', title: 'Kilka lokali? Jeden panel.',
      body: 'Jedno logowanie, wszystkie lokale, alerty do menedżera każdego z nich.',
      weeklyTitle: 'Poniedziałek, 9:00', weekly: 'Podsumowanie tygodnia ze wszystkich lokali — e-mail i powiadomienie.',
      venues: [['Bistro Pod Lipą', 4.7, '64 oceny'], ['Trattoria Wola', 4.3, '38 ocen', '2 do reakcji'], ['Kawiarnia Rynek', 4.5, '41 ocen']],
    },
    faq: {
      eyebrow: 'FAQ', title: 'Częste pytania',
      items: [
        ['Ile to kosztuje?', 'Cena zależy od liczby lokali i kart — dobieramy ją do Twojego lokalu. Konkretną propozycję przedstawimy na bezpłatnym demo, bez zobowiązań.'],
        ['Czy mogę najpierw spróbować?', 'Tak. Pierwsze 30 dni w jednym lokalu są bezpłatne, bez podawania karty płatniczej. Jeśli nie zostaniesz, karty zostają u Ciebie.'],
        ['Czego potrzebuję? Jaki sprzęt?', 'Tylko kart TapMi z kodem QR — przygotowujemy je dla Ciebie. Gość używa własnego telefonu, a Ty panelu w przeglądarce. Nic nie instalujesz.'],
        ['Ile trwa uruchomienie?', 'Zwykle do tygodnia od demo. Konfigurujemy lokal i przygotowujemy karty, Ty dodajesz tylko imiona kelnerów.'],
        ['Co widzi gość?', 'Twoje logo, pięć gwiazdek i przycisk „Oceń nas w Google” — zawsze ten sam. Opcjonalnie prywatna wiadomość i Instagram. Po polsku, ukraińsku lub angielsku.'],
        ['Czy widzicie, ile opinii dodali goście?', 'W panelu widzisz „przejścia do opinii”, czyli kliknięcia przycisku. Nie widzimy, czy gość faktycznie dodał opinię, i nie obiecujemy konkretnej liczby.'],
        ['Czy menedżer potrzebuje konta?', 'Nie. Menedżer dostaje osobisty link do alertów na telefon i e-mail. Panel i ustawienia zostają u właściciela. Jest też tryb ciemny na wieczorny serwis.'],
        ['Co z danymi i RODO?', 'Gość nie zakłada konta i nie podaje imienia ani e-maila. Zapisujemy ocenę, opcjonalny komentarz, godzinę i kartę. Członków zespołu wpisujesz tylko z imienia, a ich oceny widzisz wyłącznie Ty.'],
        ['Czy muszę podpisać długą umowę?', 'Nie. Umowa jest na czas nieokreślony z miesięcznym okresem wypowiedzenia. Zostajesz, bo to działa — a nie dlatego, że musisz.'],
      ],
    },
    cta: {
      eyebrow: 'Bezpłatne demo', title: 'Zobacz TapMi na własnym telefonie',
      body: 'Bez zobowiązań. Pokażemy wszystko na przykładzie lokalu podobnego do Twojego.',
      call: 'Zadzwoń', whatsapp: 'WhatsApp', or: 'albo zostaw kontakt:',
    },
    form: {
      name: ['Imię i nazwisko', 'np. Anna Kowalska'], venue: ['Nazwa lokalu', 'np. Bistro Pod Lipą'], city: ['Miasto', 'np. Kraków'],
      phone: ['Telefon', 'np. 600 123 456'], email: ['E-mail (opcjonalnie)', 'anna@twojlokal.pl'], message: ['Wiadomość (opcjonalnie)', 'np. Mamy 3 lokale, najlepiej po 15:00'],
      more: '+ Dodaj e-mail lub wiadomość',
      submit: 'Umów bezpłatne demo', sending: 'Wysyłanie…', required: '* pole wymagane',
      errRequired: 'Uzupełnij to pole.', errPhone: 'Sprawdź numer telefonu.', errEmail: 'Sprawdź adres e-mail.',
      successTitle: 'Dziękujemy!', success: 'Odezwiemy się w ciągu 1 dnia roboczego, żeby ustalić termin.',
      error: 'Nie udało się wysłać formularza. Spróbuj ponownie albo zadzwoń: {PHONE}.',
      privacy: 'Administratorem danych jest {COMPANY}. Używamy ich tylko, by skontaktować się w sprawie demo. Szczegóły: polityka prywatności (RODO).',
    },
    footer: { tagline: 'Zadowoleni goście, zgrany zespół.', product: 'Produkt', company: 'Kontakt', privacy: 'Polityka prywatności', language: 'Język' },
    privacyPath: '/polityka-prywatnosci/',
    privacyPage: {
      title: 'Polityka prywatności — TapMi',
      h1: 'Polityka prywatności (RODO)',
      back: '← Wróć na stronę główną',
      sections: [
        ['Administrator danych', 'Administratorem danych osobowych jest {COMPANY}{ADDRESS_LINE}. Kontakt: {CONTACT}.'],
        ['Jakie dane i po co', 'Z formularza „Umów bezpłatne demo” zbieramy imię i nazwisko, nazwę lokalu, miasto, numer telefonu oraz — jeśli je podasz — e-mail i wiadomość. Używamy ich wyłącznie, by skontaktować się w sprawie demo i przedstawić ofertę.'],
        ['Podstawa prawna', 'Art. 6 ust. 1 lit. b RODO — działania podejmowane na Twoje żądanie przed zawarciem umowy; art. 6 ust. 1 lit. f RODO — nasz uzasadniony interes, czyli kontakt w sprawie Twojego zapytania i ewentualna obrona przed roszczeniami.'],
        ['Jak długo', 'Przechowujemy dane do 12 miesięcy od ostatniego kontaktu, chyba że zawrzemy umowę — wtedy na czas jej trwania i przez okres wymagany przepisami.'],
        ['Odbiorcy', 'Dane przetwarzają w naszym imieniu dostawcy usług hostingu i poczty e-mail, wyłącznie w zakresie potrzebnym do działania formularza.'],
        ['Twoje prawa', 'Masz prawo dostępu do danych, ich sprostowania, usunięcia, ograniczenia przetwarzania, przenoszenia oraz sprzeciwu, a także prawo wniesienia skargi do Prezesa Urzędu Ochrony Danych Osobowych (UODO). Podanie danych jest dobrowolne, ale potrzebne, abyśmy mogli się z Tobą skontaktować.'],
        ['Pliki cookie', 'Ta strona nie używa plików cookie ani narzędzi śledzących.'],
      ],
    },
  },

  en: {
    lang: 'en', other: 'pl', otherLabel: 'PL', otherHref: '/', langLabel: 'Wersja polska',
    title: 'Google Reviews for Restaurants – NFC Cards | TapMi',
    description: 'An NFC card on the table: guests rate their visit in seconds and you hear about low ratings at once. Every guest invited to review you on Google.',
    nav: { how: 'How it works', owner: 'Alerts', features: 'Features', groups: 'For groups', faq: 'FAQ', login: 'Log in', cta: 'Book a demo', menu: 'Open menu' },
    skip: 'Skip to content',
    hero: {
      eyebrow: 'Google reviews & guest ratings · restaurants, cafés, hotels',
      title: 'Happy guests, a team in step.',
      lead: 'Guests rate in 5 seconds. You know instantly.',
      cta: 'Book a free demo', secondary: 'See how it works',
      chips: [['phone', 'No app'], ['shield', 'Google-safe'], ['check', 'Phone & PC']],
    },
    mock: {
      venue: 'Bistro Pod Lipą', question: 'How was your visit?', note: '+ Private note for the team', google: 'Review us on Google',
      notifTime: 'now', notifVenue: 'Bistro Pod Lipą', notifBody: 'Served by Ania · “We waited a long time for dessert.”', notifTip: 'Go to the table — listen first.',
      avg: 'Avg rating · 7 days', ratings: '58 ratings', caption: 'How TapMi works: the guest taps their phone on the card and rates; the owner gets an alert right away and sees the result in the dashboard.',
      pause: 'Pause animation', play: 'Play animation',
    },
    how: {
      eyebrow: 'How it works', title: 'Three steps, a few seconds',
      steps: [
        ['The guest taps', 'Their phone on the NFC card — or scans the QR.'],
        ['Rates with stars', 'Then the same Google invitation for everyone.'],
        ['You know instantly', 'A 1–3★ rating pings your phone.'],
      ],
    },
    owner: {
      eyebrow: 'Alerts', title: 'When something’s off, there’s still time',
      body: 'The alert arrives while the guest is still there. Go over, listen, close it with one tap.',
      small: 'Every alert reminds you: don’t mention the rating or ask to change it.',
      resolved: 'Resolved', resolvedNote: 'Dessert on the house',
    },
    google: {
      eyebrow: 'Google-safe', title: 'The same invitation for everyone',
      body: 'Every rating, 1 to 5★, sees the same Google button. The private note is an extra — never a replacement.',
      caption: 'The same button after every rating',
    },
    features: {
      eyebrow: 'Features', title: 'Everything you need', swipe: 'Swipe to see more',
      items: [
        ['phone', 'Rated in seconds', 'No app, PL/UA/EN, your logo and colours.'],
        ['bell', 'Alerts to phone and email', 'A 1–3★ rating on your phone within seconds.'],
        ['check', 'A dashboard that shows what matters', 'See what needs you first.'],
        ['users', 'Staff ratings', 'Who guests praise — fairly, from 15 ratings.'],
        ['search', 'Comments and stats', 'Search comments, export to Excel.'],
        ['heart', 'Instagram button', 'After rating: “Follow us on Instagram”.'],
      ],
    },
    groups: {
      eyebrow: 'For restaurant groups', title: 'Several venues? One dashboard.',
      body: 'One login, every venue, alerts to each venue’s manager.',
      weeklyTitle: 'Monday, 9:00', weekly: 'A weekly summary of all your venues — email and notification.',
      venues: [['Bistro Pod Lipą', 4.7, '64 ratings'], ['Trattoria Wola', 4.3, '38 ratings', '2 to follow up'], ['Kawiarnia Rynek', 4.5, '41 ratings']],
    },
    faq: {
      eyebrow: 'FAQ', title: 'Frequently asked questions',
      items: [
        ['How much does it cost?', 'It depends on how many venues and cards you need, so we tailor it to you. You’ll get a clear offer at the free demo, with no obligation.'],
        ['Can I try it first?', 'Yes. Your first 30 days at one venue are free, with no card details needed. If you decide not to continue, keep the cards.'],
        ['What do I need? Any hardware?', 'Just the TapMi cards with a QR code — we prepare them for you. Guests use their own phones and you use the dashboard in a browser. Nothing to install.'],
        ['How long does setup take?', 'Usually within a week of the demo. We set up your venue and prepare the cards — you just add your staff’s first names.'],
        ['What does the guest see?', 'Your logo, five stars and a “Review us on Google” button — always the same. Optionally a private note and Instagram. In Polish, Ukrainian or English.'],
        ['Can you see how many reviews guests posted?', 'Your dashboard shows “sent to review sites” — taps on the button. We can’t see whether the guest posted, so we never promise a number of reviews.'],
        ['Does a manager need an account?', 'No. Managers get a personal link for alerts by phone and email; the dashboard and settings stay with the owner. There’s also a dark mode for evening service.'],
        ['What about data and GDPR?', 'Guests don’t sign up or give a name or email. We store the rating, the optional comment, the time and the card. Staff are added by first name only, and only you see their ratings.'],
        ['Do I have to sign a long contract?', 'No. It’s an open-ended agreement with one month’s notice. You stay because it works, not because you have to.'],
      ],
    },
    cta: {
      eyebrow: 'Free demo', title: 'See TapMi on your own phone',
      body: 'No obligation. We’ll show you everything using a venue like yours.',
      call: 'Call', whatsapp: 'WhatsApp', or: 'or leave your details:',
    },
    form: {
      name: ['Your name', 'e.g. Anna Kowalska'], venue: ['Venue name', 'e.g. Bistro Pod Lipą'], city: ['City', 'e.g. Kraków'],
      phone: ['Phone', 'e.g. 600 123 456'], email: ['Email (optional)', 'anna@yourvenue.pl'], message: ['Message (optional)', 'e.g. We run 3 venues, best after 3 pm'],
      more: '+ Add email or message',
      submit: 'Book a free demo', sending: 'Sending…', required: '* required',
      errRequired: 'Please fill this in.', errPhone: 'Please check the phone number.', errEmail: 'Please check the email address.',
      successTitle: 'Thank you!', success: 'We’ll get back to you within 1 business day to set a time.',
      error: 'The form didn’t go through. Please try again or call us: {PHONE}.',
      privacy: 'Your data is controlled by {COMPANY} and used only to contact you about the demo. Details: privacy policy (GDPR).',
    },
    footer: { tagline: 'Happy guests, a team in step.', product: 'Product', company: 'Contact', privacy: 'Privacy policy', language: 'Language' },
    privacyPath: '/en/privacy/',
    privacyPage: {
      title: 'Privacy policy — TapMi',
      h1: 'Privacy policy (GDPR)',
      back: '← Back to the home page',
      sections: [
        ['Controller', 'The controller of your personal data is {COMPANY}{ADDRESS_LINE}. Contact: {CONTACT}.'],
        ['What data and why', 'Through the “Book a free demo” form we collect your name, venue name, city, phone number and — if you give them — your email and message. We use them only to contact you about the demo and our offer.'],
        ['Legal basis', 'Art. 6(1)(b) GDPR — steps taken at your request before entering into a contract; Art. 6(1)(f) GDPR — our legitimate interest in replying to your enquiry and defending possible claims.'],
        ['How long', 'We keep the data for up to 12 months after our last contact, unless we sign a contract — then for its duration and as long as the law requires.'],
        ['Recipients', 'Our hosting and email providers process the data on our behalf, only as needed for the form to work.'],
        ['Your rights', 'You can request access, correction, deletion, restriction or portability of your data, object to processing, and complain to the Polish data protection authority (UODO). Giving your data is optional but needed for us to contact you.'],
        ['Cookies', 'This website uses no cookies and no tracking tools.'],
      ],
    },
  },
};
