// All text on tapmi.pl, Polish and English side by side (written by the
// marketing agent from the app's real features). {PLACEHOLDERS} come from
// config.js and are filled in by build.js.
module.exports = {
  pl: {
    lang: 'pl', other: 'en', otherLabel: 'EN', otherHref: '/en/',
    title: 'Opinie Google dla restauracji – karty NFC | TapMi',
    description: 'Karta NFC na stoliku: goście oceniają wizytę w kilka sekund, a o niskiej ocenie wiesz od razu. Więcej zaproszeń do opinii Google, zgodnie z zasadami.',
    nav: { how: 'Jak to działa', features: 'Funkcje', groups: 'Dla grup lokali', google: 'Zgodność z Google', faq: 'FAQ', login: 'Zaloguj się', cta: 'Umów demo', menu: 'Menu', close: 'Zamknij' },
    hero: {
      eyebrow: 'Opinie Google i oceny gości · restauracje, kawiarnie, hotele',
      title: 'Zadowoleni goście, zgrany zespół.',
      lead: 'Gość przykłada telefon do karty TapMi i ocenia wizytę w kilka sekund. Widzisz każdą ocenę, a gdy coś nie zagra — dowiadujesz się od razu i możesz podejść, póki gość jest jeszcze przy stoliku.',
      cta: 'Umów bezpłatne demo', secondary: 'Zobacz, jak to działa',
      bullets: ['Bez aplikacji — wystarczy telefon gościa', 'Zgodne z zasadami Google — każdy gość dostaje to samo zaproszenie', 'Panel na telefonie, tablecie i komputerze'],
    },
    mock: {
      venue: 'Bistro Pod Lipą', question: 'Jak oceniasz swoją wizytę?', note: '+ Prywatna wiadomość dla zespołu', google: 'Oceń nas w Google',
      notifTime: 'teraz', notifTitle: '2★ · Bistro Pod Lipą', notifBody: 'Obsługa: Ania · „Długo czekaliśmy na deser.”', notifTip: 'Podejdź do stolika — najpierw wysłuchaj.',
      avg: 'Śr. ocena · 7 dni', ratings: '58 ocen', caption: 'Tak wygląda TapMi: strona gościa, alert na telefonie i panel właściciela.',
    },
    how: {
      eyebrow: 'Jak to działa', title: 'Karta NFC z kodem QR: trzy kroki, kilka sekund',
      steps: [
        ['Gość przykłada telefon', 'Kelner podaje kartę TapMi z rachunkiem albo leży na stoliku. Nie ma NFC? Wystarczy zeskanować kod QR.'],
        ['Ocenia w kilka sekund', 'Pięć gwiazdek, opcjonalnie prywatna wiadomość dla zespołu. Potem zaproszenie do opinii w Google — takie samo dla każdego.'],
        ['Ty wiesz, co się dzieje', 'Każda ocena trafia do panelu. Ocena 1–3★ od razu przychodzi na telefon i e-mail — do Ciebie albo menedżera zmiany.'],
      ],
    },
    features: {
      eyebrow: 'Funkcje', title: 'Wszystko, czego potrzebujesz. Nic ponad to.',
      items: [
        ['phone', 'Ocena w kilka sekund', 'Bez aplikacji i logowania. Strona mówi po polsku, ukraińsku lub angielsku — jak telefon gościa — i pokazuje Twoje logo i kolory.'],
        ['bell', 'Alert na telefon i e-mail', 'Gdy gość da 1–3★, Ty lub menedżerowie wiecie o tym w kilka sekund. Menedżer nie potrzebuje nawet konta.'],
        ['check', 'Panel, który mówi, co ważne', 'Na start: powitanie i to, co czeka na Twoją reakcję. Sprawę zamykasz jednym dotknięciem i dopisujesz notatkę.'],
        ['users', 'Oceny obsługi', 'Każdy kelner ma swoją kartę — widzisz, kogo goście chwalą i kto może potrzebować wsparcia. Porównujemy dopiero od 15 ocen.'],
        ['search', 'Komentarze i statystyki', 'Wyszukiwarka komentarzy („czekanie”, „zimne”), oceny dziennie, rozkład gwiazdek, eksport do Excela i tryb ciemny na wieczorny serwis.'],
        ['heart', 'Przycisk Instagrama', 'Po ocenie gość widzi „Obserwuj nas na Instagramie” — prosty sposób, by zostać w kontakcie.'],
      ],
    },
    owner: {
      eyebrow: 'Dla właściciela', title: 'Gdy coś nie zagra, masz jeszcze chwilę',
      body: [
        'Każdy lokal ma czasem gorszy moment — zimne danie, za długie czekanie. Z TapMi dowiadujesz się o tym od razu, a nie po fakcie.',
        'Powiadomienie przychodzi kilka sekund po ocenie: ile gwiazdek, który lokal, kto obsługiwał — i krótka podpowiedź, jak podejść do gościa.',
        'Gość wychodzi z poczuciem, że ktoś go wysłuchał. Ty oznaczasz sprawę jako załatwioną i dopisujesz notatkę, np. „deser na koszt lokalu”.',
      ],
      small: 'Każdy alert przypomina: nie wspominaj o ocenie i nie proś o jej zmianę. Chodzi o gościa, nie o gwiazdki.',
      resolved: 'Załatwione', resolvedNote: 'Deser na koszt lokalu',
    },
    google: {
      eyebrow: 'Zgodność z Google', title: 'Opinie Google zgodnie z zasadami: to samo zaproszenie dla każdego',
      body: 'Po każdej ocenie, od 1 do 5 gwiazdek, gość widzi ten sam przycisk „Oceń nas w Google”. Nie wybieramy, kogo zaprosić — zasady Google i unijne przepisy o opiniach konsumenckich na to nie pozwalają. Dzięki temu Twoje opinie są bezpieczne. Prywatna wiadomość dla zespołu to dodatkowa opcja, nigdy zamiast opinii publicznej.',
      caption: 'Ten sam przycisk przy każdej ocenie',
      honesty: 'W panelu widzisz „przejścia do opinii”, czyli kliknięcia przycisku. Nie widzimy, czy gość dodał opinię, i nie obiecujemy konkretnej liczby.',
    },
    groups: {
      eyebrow: 'Dla grup lokali', title: 'Kilka lokali? Jeden panel.',
      body: 'Jedno logowanie, wszystkie Twoje lokale. Każdy ma swój kafelek z wynikiem tygodnia, a między lokalami przełączasz się jednym kliknięciem. Alerty z danego lokalu mogą trafiać prosto do jego menedżera.',
      weeklyTitle: 'Poniedziałek, 9:00 — Twój tydzień.',
      weekly: 'E-mail i powiadomienie na telefon: oceny, średnia, przejścia do opinii, załatwione niskie oceny i najwyżej oceniana obsługa. Wszystkie lokale w jednej wiadomości.',
      venues: [['Bistro Pod Lipą', '4,7', '64 oceny'], ['Kawiarnia Rynek', '4,5', '41 ocen'], ['Trattoria Wola', '4,3', '38 ocen', '2 do reakcji']],
    },
    faq: {
      eyebrow: 'FAQ', title: 'Częste pytania',
      items: [
        ['Ile to kosztuje?', 'Cena zależy od liczby lokali i kart — dobieramy ją do Twojego lokalu. Konkretną propozycję przedstawimy na bezpłatnym demo, bez zobowiązań.'],
        ['Czy mogę najpierw spróbować?', 'Tak. Pierwsze 30 dni w jednym lokalu są bezpłatne, bez podawania karty płatniczej. Jeśli nie zostaniesz, karty zostają u Ciebie.'],
        ['Czego potrzebuję? Jaki sprzęt?', 'Tylko kart TapMi z kodem QR — przygotowujemy je dla Ciebie. Gość używa własnego telefonu, a Ty panelu w przeglądarce. Nic nie instalujesz.'],
        ['Ile trwa uruchomienie?', 'Zwykle do tygodnia od demo. Konfigurujemy lokal i przygotowujemy karty, Ty dodajesz tylko imiona kelnerów.'],
        ['Co z danymi i RODO?', 'Gość nie zakłada konta i nie podaje imienia ani e-maila. Zapisujemy ocenę, opcjonalny komentarz, godzinę i kartę. Członków zespołu wpisujesz tylko z imienia, a ich oceny widzisz wyłącznie Ty.'],
        ['Co widzi gość?', 'Twoje logo i pytanie o wizytę z pięcioma gwiazdkami. Po ocenie: podziękowanie, opcja prywatnej wiadomości dla zespołu, przycisk „Oceń nas w Google” — zawsze ten sam — i, jeśli chcesz, Instagram. Po polsku, ukraińsku lub angielsku.'],
        ['Czy muszę podpisać długą umowę?', 'Nie. Umowa jest na czas nieokreślony z miesięcznym okresem wypowiedzenia. Zostajesz, bo to działa — a nie dlatego, że musisz.'],
      ],
    },
    cta: {
      eyebrow: 'Bezpłatne demo', title: 'Zobacz TapMi na własnym telefonie',
      body: 'Bez zobowiązań. Pokażemy stronę gościa, alert i panel na przykładzie lokalu podobnego do Twojego.',
      alt: 'Wolisz porozmawiać od razu?', call: 'Zadzwoń',
    },
    form: {
      name: ['Imię i nazwisko', 'np. Anna Kowalska'], venue: ['Nazwa lokalu', 'np. Bistro Pod Lipą'], city: ['Miasto', 'np. Kraków'],
      phone: ['Telefon', 'np. 600 123 456'], email: ['E-mail (opcjonalnie)', 'anna@twojlokal.pl'], message: ['Wiadomość (opcjonalnie)', 'np. Mamy 3 lokale, najlepiej po 15:00'],
      submit: 'Umów bezpłatne demo', sending: 'Wysyłanie…', required: '* pole wymagane',
      errRequired: 'Uzupełnij to pole.', errPhone: 'Sprawdź numer telefonu.', errEmail: 'Sprawdź adres e-mail.',
      successTitle: 'Dziękujemy!', success: 'Odezwiemy się w ciągu 1 dnia roboczego, żeby ustalić termin.',
      error: 'Nie udało się wysłać formularza. Spróbuj ponownie albo zadzwoń: {PHONE}.',
      privacy: 'Administratorem danych jest {COMPANY}. Używamy ich tylko, by skontaktować się w sprawie demo. Szczegóły: polityka prywatności (RODO).',
    },
    footer: { tagline: 'Zadowoleni goście, zgrany zespół.', product: 'Produkt', company: 'Kontakt', privacy: 'Polityka prywatności' },
    langLabel: 'English version',
    privacyPath: '/polityka-prywatnosci/',
    privacyPage: {
      title: 'Polityka prywatności — TapMi',
      h1: 'Polityka prywatności (RODO)',
      back: '← Wróć na stronę główną',
      sections: [
        ['Administrator danych', 'Administratorem danych osobowych jest {COMPANY}{ADDRESS_LINE}. Kontakt: {EMAIL}, tel. {PHONE}.'],
        ['Jakie dane i po co', 'Z formularza „Umów bezpłatne demo” zbieramy imię i nazwisko, nazwę lokalu, miasto, numer telefonu oraz — jeśli je podasz — e-mail i wiadomość. Używamy ich wyłącznie, by skontaktować się w sprawie demo i przedstawić ofertę.'],
        ['Podstawa prawna', 'Art. 6 ust. 1 lit. b RODO — działania podejmowane na Twoje żądanie przed zawarciem umowy; art. 6 ust. 1 lit. f RODO — nasz uzasadniony interes, czyli kontakt w sprawie Twojego zapytania i ewentualna obrona przed roszczeniami.'],
        ['Jak długo', 'Przechowujemy dane do 12 miesięcy od ostatniego kontaktu, chyba że zawrzemy umowę — wtedy na czas jej trwania i przez okres wymagany przepisami.'],
        ['Odbiorcy', 'Dane przetwarzają w naszym imieniu dostawcy usług hostingu i poczty e-mail, wyłącznie w zakresie potrzebnym do działania formularza.'],
        ['Twoje prawa', 'Masz prawo dostępu do danych, ich sprostowania, usunięcia, ograniczenia przetwarzania, przenoszenia oraz sprzeciwu, a także prawo wniesienia skargi do Prezesa Urzędu Ochrony Danych Osobowych (UODO). Podanie danych jest dobrowolne, ale potrzebne, abyśmy mogli się z Tobą skontaktować.'],
        ['Pliki cookie', 'Ta strona nie używa plików cookie ani narzędzi śledzących.'],
      ],
    },
  },

  en: {
    lang: 'en', other: 'pl', otherLabel: 'PL', otherHref: '/',
    title: 'Google Reviews for Restaurants – NFC Cards | TapMi',
    description: 'An NFC card on the table: guests rate their visit in seconds and you hear about low ratings at once. Every guest invited to review you on Google.',
    nav: { how: 'How it works', features: 'Features', groups: 'For groups', google: 'Google-safe', faq: 'FAQ', login: 'Log in', cta: 'Book a demo', menu: 'Menu', close: 'Close' },
    hero: {
      eyebrow: 'Google reviews & guest ratings · restaurants, cafés, hotels',
      title: 'Happy guests, a team in step.',
      lead: 'Guests tap their phone on a TapMi card and rate their visit in seconds. You see every rating — and when something’s off, you hear about it right away, while the guest is still at the table.',
      cta: 'Book a free demo', secondary: 'See how it works',
      bullets: ['No app — just the guest’s phone', 'Google-safe — every guest gets the same invitation', 'Dashboard on phone, tablet and computer'],
    },
    mock: {
      venue: 'Bistro Pod Lipą', question: 'How was your visit?', note: '+ Private note for the team', google: 'Review us on Google',
      notifTime: 'now', notifTitle: '2★ · Bistro Pod Lipą', notifBody: 'Served by Ania · “We waited a long time for dessert.”', notifTip: 'Go to the table — listen first.',
      avg: 'Avg rating · 7 days', ratings: '58 ratings', caption: 'This is TapMi: the guest page, an alert on your phone and the owner dashboard.',
    },
    how: {
      eyebrow: 'How it works', title: 'An NFC card with a QR code: three steps, a few seconds',
      steps: [
        ['The guest taps', 'The waiter brings the TapMi card with the bill, or it sits on the table. No NFC? The QR code works too.'],
        ['Rates in seconds', 'Five stars, plus an optional private note for the team. Then an invitation to review you on Google — the same for everyone.'],
        ['You know what’s happening', 'Every rating lands in your dashboard. A 1–3★ rating goes straight to your phone and email — or the shift manager’s.'],
      ],
    },
    features: {
      eyebrow: 'Features', title: 'Everything you need. Nothing you don’t.',
      items: [
        ['phone', 'Rated in seconds', 'No app, no sign-up. The page speaks Polish, Ukrainian or English to match the guest’s phone, and shows your logo and colours.'],
        ['bell', 'Alerts to phone and email', 'When a guest gives 1–3★, you or your managers hear about it within seconds. Managers don’t even need a login.'],
        ['check', 'A dashboard that shows what matters', 'It opens with a greeting and whatever needs you. Close an alert with one tap and add a note.'],
        ['users', 'Staff ratings', 'Each waiter carries their own card — see who guests praise and who might need support. We only compare after 15 ratings.'],
        ['search', 'Comments and stats', 'Search comments (“wait”, “cold”), ratings per day, star breakdown, export to Excel — and dark mode for evening service.'],
        ['heart', 'Instagram button', 'After rating, guests see “Follow us on Instagram” — an easy way to stay in touch.'],
      ],
    },
    owner: {
      eyebrow: 'For the owner', title: 'When something’s off, there’s still time',
      body: [
        'Every venue has an off moment now and then — a cold plate, a long wait. With TapMi you hear about it right away, not after the fact.',
        'The alert arrives seconds after the rating: how many stars, which venue, who served — with a short tip on how to approach the guest.',
        'The guest leaves feeling heard. You mark it resolved and add a note, e.g. “dessert on the house”.',
      ],
      small: 'Every alert reminds you: don’t mention the rating or ask to change it. It’s about the guest, not the stars.',
      resolved: 'Resolved', resolvedNote: 'Dessert on the house',
    },
    google: {
      eyebrow: 'Google-safe', title: 'Every guest gets the same invitation',
      body: 'After every rating, from 1 to 5 stars, the guest sees the same “Review us on Google” button. We never pick who gets invited — Google’s policies and EU consumer-review rules don’t allow it — and that keeps your Google reviews safe. The private note for the team is an extra option, never a replacement for a public review.',
      caption: 'The same button after every rating',
      honesty: 'Your dashboard shows “sent to review sites” — taps on the button. We can’t see whether the guest posted, so we never promise a number of reviews.',
    },
    groups: {
      eyebrow: 'For restaurant groups', title: 'Several venues? One dashboard.',
      body: 'One login, all your venues. Each has its own tile with this week’s numbers, and you switch between them with one click. Alerts from each venue can go straight to its manager.',
      weeklyTitle: 'Monday, 9:00 — your week.',
      weekly: 'Email plus a phone notification: ratings, average, visits to review sites, low ratings handled and your top-rated team member. All venues in one message.',
      venues: [['Bistro Pod Lipą', '4.7', '64 ratings'], ['Kawiarnia Rynek', '4.5', '41 ratings'], ['Trattoria Wola', '4.3', '38 ratings', '2 to follow up']],
    },
    faq: {
      eyebrow: 'FAQ', title: 'Frequently asked questions',
      items: [
        ['How much does it cost?', 'It depends on how many venues and cards you need, so we tailor it to you. You’ll get a clear offer at the free demo, with no obligation.'],
        ['Can I try it first?', 'Yes. Your first 30 days at one venue are free, with no card details needed. If you decide not to continue, keep the cards.'],
        ['What do I need? Any hardware?', 'Just the TapMi cards with a QR code — we prepare them for you. Guests use their own phones and you use the dashboard in a browser. Nothing to install.'],
        ['How long does setup take?', 'Usually within a week of the demo. We set up your venue and prepare the cards — you just add your staff’s first names.'],
        ['What about data and GDPR?', 'Guests don’t sign up or give a name or email. We store the rating, the optional comment, the time and the card. Staff are added by first name only, and only you see their ratings.'],
        ['What does the guest see?', 'Your logo and a question about their visit with five stars. After rating: a thank-you, an option to send the team a private note, a “Review us on Google” button — always the same — and, if you like, Instagram. In Polish, Ukrainian or English.'],
        ['Do I have to sign a long contract?', 'No. It’s an open-ended agreement with one month’s notice. You stay because it works, not because you have to.'],
      ],
    },
    cta: {
      eyebrow: 'Free demo', title: 'See TapMi on your own phone',
      body: 'No obligation. We’ll show you the guest page, an alert and the dashboard, using a venue like yours.',
      alt: 'Prefer to talk now?', call: 'Call',
    },
    form: {
      name: ['Your name', 'e.g. Anna Kowalska'], venue: ['Venue name', 'e.g. Bistro Pod Lipą'], city: ['City', 'e.g. Kraków'],
      phone: ['Phone', 'e.g. 600 123 456'], email: ['Email (optional)', 'anna@yourvenue.pl'], message: ['Message (optional)', 'e.g. We run 3 venues, best after 3 pm'],
      submit: 'Book a free demo', sending: 'Sending…', required: '* required',
      errRequired: 'Please fill this in.', errPhone: 'Please check the phone number.', errEmail: 'Please check the email address.',
      successTitle: 'Thank you!', success: 'We’ll get back to you within 1 business day to set a time.',
      error: 'The form didn’t go through. Please try again or call us: {PHONE}.',
      privacy: 'Your data is controlled by {COMPANY} and used only to contact you about the demo. Details: privacy policy (GDPR).',
    },
    footer: { tagline: 'Happy guests, a team in step.', product: 'Product', company: 'Contact', privacy: 'Privacy policy' },
    langLabel: 'Wersja polska',
    privacyPath: '/en/privacy/',
    privacyPage: {
      title: 'Privacy policy — TapMi',
      h1: 'Privacy policy (GDPR)',
      back: '← Back to the home page',
      sections: [
        ['Controller', 'The controller of your personal data is {COMPANY}{ADDRESS_LINE}. Contact: {EMAIL}, phone {PHONE}.'],
        ['What data and why', 'Through the “Book a free demo” form we collect your name, venue name, city, phone number and — if you give them — your email and message. We use them only to contact you about the demo and our offer.'],
        ['Legal basis', 'Art. 6(1)(b) GDPR — steps taken at your request before entering into a contract; Art. 6(1)(f) GDPR — our legitimate interest in replying to your enquiry and defending possible claims.'],
        ['How long', 'We keep the data for up to 12 months after our last contact, unless we sign a contract — then for its duration and as long as the law requires.'],
        ['Recipients', 'Our hosting and email providers process the data on our behalf, only as needed for the form to work.'],
        ['Your rights', 'You can request access, correction, deletion, restriction or portability of your data, object to processing, and complain to the Polish data protection authority (UODO). Giving your data is optional but needed for us to contact you.'],
        ['Cookies', 'This website uses no cookies and no tracking tools.'],
      ],
    },
  },
};
